# Generated by Django 6.0.3 on 2026-04-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0008_home_timestamps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='bio',
            field=models.TextField(blank=True, default='', help_text='Редактируется самим спикером из личного кабинета.', verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='speaker',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Связка устанавливается вручную администратором.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='speaker', to=settings.AUTH_USER_MODEL, verbose_name='Привязанный пользователь'),
        ),
    ]
