# Generated by Django 6.0.3 on 2026-04-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0009_speaker_bio_speaker_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='speaker',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/speakers/'),
        ),
    ]
