# Generated by Django 6.0.3 on 2026-05-05 20:29

from django.db import migrations, models


def sync_speaker_auth_status(apps, schema_editor):
    Speaker = apps.get_model("starlift", "Speaker")
    Speaker.objects.exclude(user_id__isnull=True).update(status="authorized")
    Speaker.objects.filter(user_id__isnull=True).update(status="unauthorized")


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0010_speaker_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='status',
            field=models.CharField(choices=[('unauthorized', 'Неавторизован'), ('authorized', 'Авторизован')], default='unauthorized', help_text='Неавторизован — нет привязки к аккаунту; Авторизован — связан с пользователем платформы.', max_length=50, verbose_name='Статус'),
        ),
        migrations.RunPython(sync_speaker_auth_status, migrations.RunPython.noop),
    ]
