# Generated by Django 6.0.3 on 2026-05-09 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0012_resync_speaker_link_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('past', 'Прошедшее'), ('future', 'Предстоящее')], default='future', max_length=50),
        ),
    ]
