# Generated by Django 6.0.3 on 2026-05-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0013_alter_event_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='nps',
            field=models.FloatField(default=0.0),
        ),
    ]
