# Generated by Django 6.0.3 on 2026-05-09 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0014_alter_speaker_nps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('create', 'Создание мероприятия'), ('join', 'Заявка на участие')], max_length=16)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=16)),
                ('topic', models.CharField(blank=True, default='', max_length=200)),
                ('comment', models.TextField(blank=True, default='')),
                ('proposed_title', models.CharField(blank=True, default='', max_length=200)),
                ('proposed_description', models.TextField(blank=True, default='')),
                ('proposed_event_date', models.DateField(blank=True, null=True)),
                ('proposed_location', models.CharField(blank=True, default='', max_length=200)),
                ('proposed_link', models.CharField(blank=True, default='', max_length=500)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='starlift.event')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_event_requests', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_requests', to='starlift.speaker')),
            ],
            options={
                'db_table': 'starlift_event_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='starlift_ev_status_9a38f6_idx')],
            },
        ),
    ]
