# Generated by Django 6.0.3 on 2026-05-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0015_eventrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='stack',
            field=models.TextField(blank=True, default=''),
        ),
    ]
