# Generated by Django 6.0.3 on 2026-05-21 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0016_alter_speaker_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='starlift.speaker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'starlift_speaker_like',
                'indexes': [models.Index(fields=['user', 'speaker'], name='starlift_sp_user_id_358ad7_idx')],
                'unique_together': {('user', 'speaker')},
            },
        ),
    ]
