# Generated by Django 6.0.3 on 2026-05-21 19:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0017_speakerlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerEventRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка (0–10)')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_ratings', to='starlift.event', verbose_name='Мероприятие')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ratings', to='starlift.speaker', verbose_name='Спикер')),
            ],
            options={
                'verbose_name': 'Оценка мероприятия от спикера',
                'verbose_name_plural': 'Оценки мероприятий от спикеров',
                'db_table': 'starlift_speaker_event_rating',
                'indexes': [models.Index(fields=['event', 'speaker'], name='starlift_sp_event_i_f8e9d5_idx')],
                'unique_together': {('event', 'speaker')},
            },
        ),
    ]
