# Generated by Django 6.0.3 on 2026-05-22 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0019_speakerapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='application_deadline',
            field=models.DateField(blank=True, help_text='Если задан и не прошёл — спикеры могут подавать заявки сами. Иначе только через приглашение DevRel.', null=True, verbose_name='Дедлайн подачи заявок'),
        ),
        migrations.CreateModel(
            name='EventInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает ответа'), ('accepted', 'Принято'), ('declined', 'Отклонено'), ('cancelled', 'Отменено DevRel')], db_index=True, default='pending', max_length=16)),
                ('message', models.TextField(blank=True, default='')),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='starlift.event')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_event_invitations', to=settings.AUTH_USER_MODEL)),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='starlift.speaker')),
            ],
            options={
                'db_table': 'starlift_event_invitation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='starlift_ev_status_6a7edb_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('event', 'speaker'), name='uniq_pending_event_invitation')],
            },
        ),
    ]
