# Generated by Django 6.0.3 on 2026-05-22 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starlift', '0020_event_application_deadline_eventinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='format',
            field=models.CharField(blank=True, choices=[('online', 'Онлайн'), ('offline', 'Офлайн'), ('hybrid', 'Гибрид')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='presentation',
            field=models.FileField(blank=True, null=True, upload_to='events/presentations/'),
        ),
        migrations.AddField(
            model_name='event',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='event',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'На верификации'), ('verified', 'Подтверждено'), ('rejected', 'Отклонено')], db_index=True, default='verified', max_length=16),
        ),
        migrations.AddField(
            model_name='event',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='events/photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='starlift.event')),
            ],
            options={
                'db_table': 'starlift_event_photo',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
