# Generated by Django 6.0.3 on 2026-05-21 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_kind', models.CharField(choices=[('user', 'user'), ('guest', 'guest')], max_length=8)),
                ('guest_email', models.EmailField(blank=True, default='', max_length=254)),
                ('guest_name', models.CharField(blank=True, default='', max_length=120)),
                ('guest_token_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('guest_notified_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_sender_kind', models.CharField(blank=True, default='', max_length=8)),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_ticket',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_read_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_read',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_kind', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('guest', 'guest'), ('system', 'system')], max_length=8)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket')),
            ],
            options={
                'db_table': 'support_message',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', '-last_message_at'], name='support_tic_status_1ebba2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['author_user', '-last_message_at'], name='support_tic_author__1c5e23_idx'),
        ),
        migrations.AddIndex(
            model_name='supportread',
            index=models.Index(fields=['user', 'ticket'], name='support_rea_user_id_bf5001_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supportread',
            unique_together={('ticket', 'user')},
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_mes_ticket__b9f841_idx'),
        ),
    ]
