# Generated by Django 6.0.3 on 2026-04-24 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('speaker', 'Спикер'), ('guest', 'Гость')], default='speaker', max_length=16),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('speaker', 'Спикер'), ('guest', 'Гость')], default='speaker', max_length=16),
        ),
    ]
