"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-$!y7q&gyioy-19s!8_5+vlbf@czrczz^v!w8#bd35!f)%(bxh!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

_default_hosts = "127.0.0.1,localhost,192.168.1.126,.ngrok-free.app,.ngrok-free.dev"
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', _default_hosts).split(',') if h.strip()]

_default_csrf = "https://*.ngrok-free.app,https://*.ngrok-free.dev"
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', _default_csrf).split(',') if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'starlift',
    'assistant',
]

USE_OBJECT_STORAGE = os.getenv("USE_OBJECT_STORAGE", "false").lower() == "true"
if USE_OBJECT_STORAGE:
    INSTALLED_APPS.append("storages")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'starlift.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.header_avatar_url',
            ],
        },
    },
]

WSGI_APPLICATION = 'starlift.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.password_validators.NotOnlySpecialCharsValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'accounts.auth_backends.UsernameOrEmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGIN_URL = '/auth/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/auth/login/'

PASSWORD_RESET_TIMEOUT = 60 * 60  # 1 hour

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_HTTPONLY = False  # CSRF cookie is read by JS for AJAX
CSRF_COOKIE_SAMESITE = 'Lax'
_secure_cookies_default = 'False' if DEBUG else 'True'
SESSION_COOKIE_SECURE = os.environ.get('SESSION_COOKIE_SECURE', _secure_cookies_default).lower() == 'true'
CSRF_COOKIE_SECURE = os.environ.get('CSRF_COOKIE_SECURE', _secure_cookies_default).lower() == 'true'

EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'localhost')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'false').lower() == 'true'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() == 'true'
EMAIL_TIMEOUT = int(os.getenv('EMAIL_TIMEOUT', '10'))
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'no-reply@starlift.local')
SITE_URL = os.getenv('SITE_URL', 'http://127.0.0.1:8000')
SITE_NAME = 'StarLift'

# Prefer SSL if both flags are set by mistake.
if EMAIL_USE_SSL and EMAIL_USE_TLS:
    EMAIL_USE_TLS = False

# Auth tuning — exposed for tests and ops
ACCOUNTS_LOCKOUT_THRESHOLD = int(os.getenv('ACCOUNTS_LOCKOUT_THRESHOLD', '6'))
ACCOUNTS_LOCKOUT_WINDOW_SECONDS = int(os.getenv('ACCOUNTS_LOCKOUT_WINDOW_SECONDS', '60'))
ACCOUNTS_INVITE_TTL_DAYS = int(os.getenv('ACCOUNTS_INVITE_TTL_DAYS', '7'))
ACCOUNTS_EMAIL_CHANGE_TTL_HOURS = int(os.getenv('ACCOUNTS_EMAIL_CHANGE_TTL_HOURS', '24'))
ACCOUNTS_RESET_EMAIL_MIN_INTERVAL_SECONDS = int(os.getenv('ACCOUNTS_RESET_EMAIL_MIN_INTERVAL_SECONDS', '300'))


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

if USE_OBJECT_STORAGE:
    STORAGE_ENDPOINT_URL = os.getenv("STORAGE_ENDPOINT_URL", "").strip()
    STORAGE_BUCKET_NAME = os.getenv("STORAGE_BUCKET_NAME", "").strip()
    STORAGE_ACCESS_KEY = os.getenv("STORAGE_ACCESS_KEY", "").strip()
    STORAGE_SECRET_KEY = os.getenv("STORAGE_SECRET_KEY", "").strip()
    STORAGE_REGION = os.getenv("STORAGE_REGION", "").strip()
    STORAGE_PUBLIC_BASE_URL = os.getenv("STORAGE_PUBLIC_BASE_URL", "").strip()
    STORAGE_ADDRESSING_STYLE = os.getenv("STORAGE_ADDRESSING_STYLE", "auto").strip() or "auto"

    if not STORAGE_BUCKET_NAME:
        raise RuntimeError("USE_OBJECT_STORAGE=true requires STORAGE_BUCKET_NAME")
    if not STORAGE_ACCESS_KEY or not STORAGE_SECRET_KEY:
        raise RuntimeError("USE_OBJECT_STORAGE=true requires STORAGE_ACCESS_KEY and STORAGE_SECRET_KEY")

    AWS_ACCESS_KEY_ID = STORAGE_ACCESS_KEY
    AWS_SECRET_ACCESS_KEY = STORAGE_SECRET_KEY
    AWS_STORAGE_BUCKET_NAME = STORAGE_BUCKET_NAME
    AWS_S3_REGION_NAME = STORAGE_REGION or None
    AWS_S3_ENDPOINT_URL = STORAGE_ENDPOINT_URL or None
    AWS_S3_ADDRESSING_STYLE = STORAGE_ADDRESSING_STYLE
    AWS_S3_SIGNATURE_VERSION = "s3v4"
    AWS_DEFAULT_ACL = None
    AWS_QUERYSTRING_AUTH = False
    AWS_S3_FILE_OVERWRITE = False

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

    if STORAGE_PUBLIC_BASE_URL:
        storage_base = STORAGE_PUBLIC_BASE_URL.rstrip("/")
        custom_domain = storage_base.replace("https://", "").replace("http://", "")
        AWS_S3_CUSTOM_DOMAIN = custom_domain
        MEDIA_URL = f"{storage_base}/"
    else:
        MEDIA_URL = "/media/"
else:
    MEDIA_URL = '/media/'

# Legal documents
LEGAL_DOC_VERSION = "2026-05-10"

